#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# WINDOWS is set under Git Bash, MSYS2, and Cygwin: a POSIX shell on a machine
# that is not POSIX. There chmod grants nothing, a browser needs a Windows
# opener, and access to a file is an ACL. Every branch below that reads this
# leaves the POSIX path exactly as it was.
WINDOWS=""
case "$(uname -s 2>/dev/null || true)" in
  MINGW*|MSYS*|CYGWIN*) WINDOWS=1 ;;
esac

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
#
# cmd start comes first on Windows. explorer.exe opens the page and then
# answers non-zero anyway, so it fired the warning below on every run and told
# the human the browser had failed while the page was in front of them. The
# same explorer call is the WSL fallback when wslview is missing, so its exit
# code is discarded there too.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   [[ -n "$WINDOWS" ]];                   then cmd //c start "" "$url"
    elif command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url" || true
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  # The copy holds every token saved so far, so an interrupt between the
  # redirect and the mv must not leave it on disk.
  trap 'rm -f "$tmp"' RETURN
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# finish shows a closing summary of everything configured. It does not clear the
# screen, so the tk doctor output just above it stays on screen.
finish() {
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# This wizard installs the Superpowers skills, then writes the tokens tk needs
# into secrets.env. tk reads that file itself, so a token never goes to the
# terminal or to a transcript.
#
# Run one step with setup.sh superpowers, azure, jira, github, or figma. Name
# several to run several: setup.sh azure github.
#
# A bare run does the Superpowers stage only. A token stage has to be named,
# because a run needs one provider and the other three questions are noise. The
# skill runs the stage the provider a ticket lives on needs, when it needs it.

WANT="${*:-superpowers}"
want() { [[ " $WANT " == *" $1 "* ]]; }

for provider in "$@"; do
  case "$provider" in
    superpowers|azure|jira|github|figma) ;;
    *)
      warn "Unknown step: $provider"
      say "Use superpowers, azure, jira, github, or figma."
      say "No argument runs the superpowers step only."
      exit 1
      ;;
  esac
done

ENV_FILE="$HOME/.claude/ticket-workflow/secrets.env"

# Windows grants access by ACL. chmod there sets the read-only attribute and
# nothing else, so a file this wizard reported as mode 600 read back as 0o666
# in python, and tk refused to load it with a fix line no chmod could carry
# out. icacls is the real lock: /inheritance:r drops the entries the user
# profile passes down, and /grant:r leaves this account and no other. (OI)(CI)
# on the directory hands the same rule to every file created inside it, which
# covers each new copy the library writes through TMPDIR and then moves into
# place.
#
# The grant is full control, not read and write. Least privilege against
# yourself buys nothing here, because the owner of a file can raise its own
# rights whenever it likes, and a narrower grant leans on the delete-child
# right of the parent for every replacement the library writes.
lock_dir() {
  chmod 700 "$1"
  [[ -n "$WINDOWS" ]] || return 0
  icacls "$(cygpath -w "$1")" /inheritance:r \
    /grant:r "${USERNAME:-$(whoami)}:(OI)(CI)(F)" >/dev/null 2>&1 \
    || warn "could not restrict $1 to your account. Check it by hand."
}

lock_file() {
  chmod 600 "$1"
  [[ -n "$WINDOWS" ]] || return 0
  icacls "$(cygpath -w "$1")" /inheritance:r \
    /grant:r "${USERNAME:-$(whoami)}:(F)" >/dev/null 2>&1 \
    || warn "could not restrict $1 to your account. Check it by hand."
}

# umask 077 comes first, so the directory arrives at 0700 and the file at 0600
# from the first byte. Each lock repairs a directory or a file that an earlier
# run left with a wider mode. mkdir -p leaves the mode of a directory that is
# already there, so the lock does that repair.
umask 077
mkdir -p "$(dirname "$ENV_FILE")"
lock_dir "$(dirname "$ENV_FILE")"
touch "$ENV_FILE"
lock_file "$ENV_FILE"

# The library builds each new copy of the file with mktemp, then moves it into
# place. TMPDIR keeps that copy in a .tmp subdirectory of the config directory.
# So no token passes through /tmp, and the move stays a rename on one
# filesystem. The browser that open_url starts inherits TMPDIR, so its temp
# files land in .tmp and never beside secrets.env. The directory is locked
# after it is created, so a copy holding a token is never readable by another
# account, not even for the moment before the move.
TMPDIR="$(dirname "$ENV_FILE")/.tmp"
mkdir -p "$TMPDIR"
lock_dir "$TMPDIR"
export TMPDIR

TOTAL_STAGES=1
for provider in superpowers azure jira github figma; do
  want "$provider" && TOTAL_STAGES=$((TOTAL_STAGES + 1))
done

banner "Ticket workflow setup"

# curl_cfg prints one line for curl --config -. The credential reaches curl on a
# pipe, so it never sits in the command line that ps shows. The quoted form
# keeps a space or a # in the value, and the two substitutions escape the only
# characters that form treats as special.
curl_cfg() {
  local value="$2"
  value=${value//\\/\\\\}
  value=${value//\"/\\\"}
  printf '%s = "%s"\n' "$1" "$value"
}

# The methodology this skill runs on. Two routes install it, and this stage
# picks one.
#
# The Claude Code plugin adds a session-start hook that loads
# using-superpowers on turn one, so it wins when the claude CLI is here. It
# reaches Claude Code only, and it names the skills superpowers:<name>.
#
# The skills CLI copies the same folders into ~/.agents/skills, which Claude
# Code, Codex, Cursor, and Copilot all read, so it covers a machine that runs
# more than one agent. It names the skills <name>, with no prefix.
#
# Neither route needs a token. Both routes get checked before either installs,
# because two copies give every skill two names and then drift apart.
superpowers_by_hand() {
  say "Install it one of these ways, then restart your agent:"
  note "  /plugin install superpowers@claude-plugins-official   (Claude Code)"
  note "  npx skills add obra/superpowers -g                    (any agent)"
  SKIPPED+=("install the superpowers skills")
}

if want superpowers; then
  stage "Superpowers methodology"
  say "This skill runs the Superpowers workflow, so it needs those skills."
  if claude plugin list 2>/dev/null | grep -q 'superpowers@'; then
    say "The plugin is installed. Nothing to do."
  elif [[ -d "$HOME/.agents/skills/using-superpowers" ]] \
    || [[ -d "$HOME/.claude/skills/using-superpowers" ]]; then
    say "The skills are installed. Nothing to do."
  elif command -v claude >/dev/null 2>&1; then
    step "Installing superpowers@claude-plugins-official."
    # --yes is required here, because stdout is not a terminal under an agent
    if claude plugin install superpowers@claude-plugins-official --yes >/dev/null 2>&1; then
      say "Installed. A restart of Claude Code loads it."
    else
      warn "The install did not finish."
      superpowers_by_hand
    fi
  elif command -v npx >/dev/null 2>&1; then
    step "Installing the superpowers skills with npx skills."
    # -g installs for the agent this runs under, and for ~/.agents/skills. The
    # second -y answers the prompts, because stdout is not a terminal under an
    # agent. Leave out -a: the CLI detects the agent and targets that one.
    if npx -y skills add obra/superpowers -g -y >/dev/null 2>&1; then
      say "Installed to ~/.agents/skills. A restart of your agent loads them."
    else
      warn "The install did not finish."
      superpowers_by_hand
    fi
  else
    warn "No claude CLI and no npx, so this step cannot install anything."
    superpowers_by_hand
  fi
fi

if want azure; then
  stage "Azure DevOps personal access token"
  say "This token reads work items, writes comments and states, and pushes code."
  # The org names the account the token belongs to, and it reaches the token
  # page and the verify call below. No default can be right for anybody, so ask.
  # The value stays out of secrets.env on purpose: tk adds every value in that
  # file to its scrub list, and the org name belongs in ordinary output.
  AZDO_ORG="${AZDO_ORG:-}"
  [[ -n "$AZDO_ORG" ]] \
    || ask AZDO_ORG "Your Azure DevOps organization, the name after dev.azure.com/:"
  if [[ -z "$AZDO_ORG" ]]; then
    warn "No organization, so this stage cannot open the token page."
    SKIPPED+=("set up the Azure token: re-run scripts/setup.sh azure")
  else
    step "On the page that opens, select New Token."
    step "Scopes: Work Items (Read, write & manage), Code (Read & write), Build (Read)."
    note "Editing the scopes later keeps the same value, so you do not re-paste it."
    open_url "https://dev.azure.com/$AZDO_ORG/_usersSettings/tokens"
    ask AZDO_USER "Your Azure account email:"
    ask_secret AZDO_PAT "Paste the token:"
    write_env AZDO_USER "$AZDO_USER"
    write_env AZDO_PAT "$AZDO_PAT"
    if curl_cfg user ":$AZDO_PAT" \
        | curl -sf --config - \
          "https://dev.azure.com/$AZDO_ORG/_apis/connectionData?api-version=7.1-preview" \
        | grep -q authenticatedUser; then
      say "Verified. The token reads connectionData."
    else
      say "The token did not verify. Check the scopes, then run this stage again."
    fi
  fi
fi

if want jira; then
  stage "Jira API token"
  say "Jira Cloud uses Basic auth: your account email plus an API token."
  # The site is the host the verify call below reads. The same rule as the
  # Azure org: no default can be right, and the value stays out of secrets.env.
  JIRA_SITE="${JIRA_SITE:-}"
  [[ -n "$JIRA_SITE" ]] \
    || ask JIRA_SITE "Your Atlassian site, for example acme.atlassian.net:"
  if [[ -z "$JIRA_SITE" ]]; then
    warn "No site, so this stage cannot verify a token."
    SKIPPED+=("set up the Jira token: re-run scripts/setup.sh jira")
  else
    step "On the page that opens, select Create API token."
    step "Name it agent-ticket-workflow. Copy the value now, because Jira shows it once."
    open_url "https://id.atlassian.com/manage-profile/security/api-tokens"
    ask JIRA_EMAIL "Your Atlassian account email:"
    ask_secret JIRA_TOKEN "Paste the API token:"
    write_env JIRA_EMAIL "$JIRA_EMAIL"
    write_env JIRA_TOKEN "$JIRA_TOKEN"
    if curl_cfg user "$JIRA_EMAIL:$JIRA_TOKEN" \
        | curl -sf --config - "https://$JIRA_SITE/rest/api/3/myself" \
        | grep -q accountId; then
      say "Verified. The token reads your account."
    else
      say "The token did not verify. Check the email and the token."
      say "If your organization blocks API tokens, ask an administrator to"
      say "allow one. This tool reads Jira through the API and nothing else."
    fi
  fi
fi

if want github; then
  stage "GitHub personal access token"
  say "This token reads issues, writes comments, and opens pull requests."
  step "On the page that opens, select Generate new token (classic)."
  step "Scope: repo. Add read:org when the repository belongs to an organization."
  step "After you create it, select Configure SSO and authorize the organization."
  open_url "https://github.com/settings/tokens"
  ask_secret GH_TOKEN "Paste the token:"
  write_env GH_TOKEN "$GH_TOKEN"
  if curl_cfg header "Authorization: Bearer $GH_TOKEN" \
      | curl -sf --config - -H "User-Agent: agent-ticket-workflow" \
        https://api.github.com/user \
      | grep -q '"login"'; then
    say "Verified. The token reads your account."
    say "A token that reads the account can still fail on the repository."
    say "tk doctor makes that call for every project."
  else
    say "The token did not verify. Check the scope and the SSO authorization."
  fi
fi

if want figma; then
  stage "Figma personal access token"
  say "This token reads the frames a ticket links to."
  step "Open Settings, then Security, then Personal access tokens."
  step "Scope: File content, Read only. Copy the value now."
  open_url "https://www.figma.com/settings"
  ask_secret FIGMA_TOKEN "Paste the token:"
  write_env FIGMA_TOKEN "$FIGMA_TOKEN"
  if curl_cfg header "X-Figma-Token: $FIGMA_TOKEN" \
      | curl -sf --config - https://api.figma.com/v1/me \
      | grep -q email; then
    say "Verified. The token reads your account."
  else
    say "The token did not verify. Check the scope."
  fi
fi

stage "Lock the file and run the check"
lock_file "$ENV_FILE"
if [[ -n "$WINDOWS" ]]; then
  say "Wrote $ENV_FILE. Your account alone can read it."
else
  say "Wrote $ENV_FILE with mode 600."
fi

# tk carries a python3 shebang, and a shebang needs that exact name on PATH.
# A stock Windows install ships python.exe and py.exe and no python3, and the
# name python3 there is often the Microsoft Store stub, which prints an advert
# and exits 9009. So name the interpreter and pass the file to it. PY is an
# array because the launcher takes an argument of its own.
PY=()
python_cmd() {
  local candidates=(python3 python) candidate
  [[ -n "$WINDOWS" ]] && candidates=(python py python3)
  for candidate in "${candidates[@]}"; do
    if command -v "$candidate" >/dev/null 2>&1; then
      PY=("$candidate")
      [[ "$candidate" == py ]] && PY=(py -3)
      return 0
    fi
  done
  return 1
}

TK="$(dirname "$0")/tk"
if [[ ! -f "$TK" ]]; then
  warn "No tk beside this script at $TK."
  say "Your tokens are saved. Run tk doctor once tk is in place."
  finish
  exit 1
fi
if ! python_cmd; then
  warn "No python on PATH, so tk cannot run."
  say "Install Python 3.11 or newer, then run tk doctor."
  SKIPPED+=("install python 3.11 or newer, then run tk doctor")
  finish
  exit 1
fi

# doctor reads every profile on disk. With none, its answer is "no project
# profiles found", which reads as a failed setup right after a token verified.
# A profile is not this wizard's job: tk init writes one when a ticket needs it.
shopt -s nullglob
profiles=("$HOME/.claude/ticket-workflow/projects"/*/config.json)
shopt -u nullglob
if (( ${#profiles[@]} == 0 )); then
  say "No project profile yet, so there is nothing more to check."
  say "The skill writes one with tk init the first time a ticket needs it."
  finish
  exit 0
fi

say "tk doctor checks every provider, not only the one you set up now."
say "A gap in another provider is a separate fix, not a fault of this run."
status=0
"${PY[@]}" "$TK" doctor || status=$?
if (( status != 0 )); then
  say "tk doctor found gaps. The output above names each fix."
  finish
  exit "$status"
fi
finish
